name: Delövning 1 - Minimal Pipeline

on:
  # ska startas manuellt
  workflow_dispatch:
jobs:
  print-info:
    runs-on: # vilken runner?
    steps:
      - name: # namnge steget
        run: # vad som ska göras
